name = "ha-github-bot"
main = "src/index.ts"
compatibility_date = "2025-05-06"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
ENVIRONMENT = "production"
BOT_SLUG = "ha-bot"
